### ISSUE TITLE
File changes

### ISSUE THREAD

**Issue by tmitchell1** [GoMexSI/interaction-data#10]
Attached are the files with the changes (addition / deletion of columns & renaming). Also attached is a file describing all the changes.
[database changes.xlsx](https://github.com/GoMexSI/interaction-data/files/354999/database.changes.xlsx)
[csv files.zip](https://github.com/GoMexSI/interaction-data/files/355001/csv.files.zip)

As soon as I have the ok, I can upload them.

**Comment by tmitchell1** [comment]
Update:

There were some more changes needed. The latest version of all the changes is attached.
[database changes.xlsx](https://github.com/GoMexSI/interaction-data/files/386482/database.changes.xlsx)

**Comment by jhpoelen** [comment]
@tmitchell1 thanks for sharing the changes in advance.

Here's some comments:
- in `Predators.csv` column `POP _TOT_PRED` has a space after `POP`
- I don't understand why you are prefixing all predator columns with PRED_ -> to me this is already clear from the fact that the table/file is called `Predators.csv`. Same goes for PREY_ prefixes.
- If you do stick with PRED_/PREY_ prefixes, suggest to apply it consistently: e.g. DATABASE_PRED_NAME --> PRED_DATABASE_NAME and SOURCE_PRED_NAME --> PRED_SOURCE_NAME. Also, why do fields like POP_ do not have the PRED prefix?
- suggest to use international 2015-04-25 (see https://en.wikipedia.org/wiki/ISO_8601) instead of us specific date format 4/25/2015 . 
- suggest to use LAST_MODIFIED_DATE and LAST_MODIFIED_BY  instead of MODIFY_DATE / DATA_MODIFIER
- what is the difference between EDITED and MODIFIED? 
- suggest to use CREATED_DATE / CREATED_BY instead of ENTRY_DATE/ENTRY_PERSON

**Comment by jsimons9** [comment]
Hi Jorrit,

  Thanks for the comments.

  I think the PRED and PREY prefixes came about when we started to add those columns to the csv download and the names were the same in the two spreadsheets, but they would be in the same csv file in the download, so needed to be differentiated.

  I do not remember where we are using the date – I know we split the date to year – month – day in the location and station spreadsheets.

  The edited by column is for edits to the data before it is uploaded.  The revision column is for revisions done after it is uploaded.

  Those six columns follow the format used by Fishbase and SeaLifeBase.

Hope this helps.

Jim

**Comment by jhpoelen** [comment]
@jsimons9 Thanks for your reply and clarifications. 

The fields generated by the GloBI data download are separate from the fields in the GoMexSI column names. So, technically, we don't need these on the GoMexSI side. GloBI knows how to differentiate data coming from the Prey.csv and Predators.csv files.

Please let me know which csv files you'd like me to use to implement the necessary changes for the updated GoMexSI column names. Once I have the changes ready, @tmitchell1 and I can coordinate the upload such that we have a seamless transition. Am open to discussing by voice if this is easier for you guys.

**Comment by tmitchell1** [comment]
@jhpoelen 

I have almost finished updating all the csv files that have already been uploaded. I just haven't sync's them yet. When I have finished the updates, should I send the files to you or sync them from here?

There is still a lot of local stuff to change. Once each one is done, it would be separate uploads as before.

**Comment by jhpoelen** [comment]
@tmitchell1 please attach a zip file of your local updated csv files to this issue prior to sync-ing. This would allow me to make necessary change in GloBI. Once these changes are in, we can coordinate GloBI / GoMexSI sync. Looking forward to receiving an updated version of the csv zip file.

**Comment by jhpoelen** [comment]
@tmitchell1 I am assuming this issue has been addressed. Please re-open this issue if this is not the case.
