### ISSUE TITLE
Prey list

### ISSUE THREAD

**Issue by tmitchell1** [GoMexSI/interaction-data#3]
In the Prey list under the DATABASE_PREY_NAME COLUMN:
Errors are being created when "NA" is entered into this column. There are some instances where there will be no entry applicable in this column. Examples: when a stomach is empty, the food/matter/other is not identified as anything specific, the sample is mutilated and not used, etc.
We need to come up with an accepted term for these instances. Any suggestions?

**Comment by jsimons9** [comment]
Jorrit, I am assuming that you have the list of miscellaneous categories that we are using to describe the prey.  Theresa and I were looking at the list this morning and are going to suggest some new categories to cover the issues that Theresa has raised.  Any thoughts you may have are also welcomed. Thanks.
Jim
PS  Is the miscellaneous prey clasification list on github where we can edit it??

**Comment by jhpoelen** [comment]
Hey @jsimons9 and @tmitchell1 

I am happy to see that you are fixing data issues left and right using the feedback that was generated by GloBI.

About the term / name mapping: I leave it up to you to pick a good descriptive term for hard to identify stomach items. I would suggest to promote consistent usage of these terms within GoMexSI. It does help to use an established ontology (e.g. Uberon for body parts/ life stages http://uberon.github.io/, EnvO http://environmentontology.org/ for inorganic matter and any established taxonomies for organisms) to make it easier for others (like GloBI) to understand what the term means. If terms are used in a GoMexSI context only, they should be documented somewhere, perhaps in the README.md of the github repository.

Needless to say: picking terms is hard and using terms consistently is even harder. This is why I like the idea of re-using existing vocabularies. To make it clear that an external term is used, you might want to consider including term/ taxon ids as a separate column in the data files. This would help remove ambiguity and make the terms easier to ingest by computers.

As far as the internal GloBI mapping files go: these files are used to correct / change terms in data sources that are hard to change so this doesn't really apply to GoMexSI, since it is under active development.

I hope this makes sense,
-jorrit
